version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/catsDB
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catsDB
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge